# .streamlit/secrets.toml
DATABASE_URL = "postgresql://postgres:Srimurni1426@db.okndwthzywdhkhsutioy.supabase.co:5432/postgres?sslmode=require&connect_timeout=10"
APP_PASSWORD = "opsional-untuk-login-app"
