DATABASE_URL = "postgresql://postgres.okndwthzywdhkhsutioy:Srimurni1426@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require&connect_timeout=10"
APP_PASSWORD = "opsional-untuk-login-app"
